FlaskApp/appFlask/__init__.py
# ESTO SIRVE PARA CONECTAR LA BASE DE DATOS 
import mysql.connector  # IMPORTAMOS LO QUE HEMOS INSTALADO PIP INSTALL MYSQL.......
from flask import Flask

# db = list()
database = mysql.connector.connect( # LLAMAMOS AL FUNCION CONNECT PARA CONECTARNOS
    host ='bqxo2nyaltlkfb7xfuft-mysql.services.clever-cloud.com', #NUESTRO HOST, ESTA EN EL DOCKER COMPOSE
    port = 3306,
    user ='uzb8hewphwelnsnw', #USUARIO QUE USAMOS NOSOTROS
    password ='YelZ440RYDQGLOlx4leb', #CONTRASEÑA CON LA QUE NOS CONECTAMOS
    database='bqxo2nyaltlkfb7xfuft'
) 



def create_app():
    app = Flask(__name__)
    app.debug = True
    

    from .routes import routes

    app.register_blueprint(routes.app)

    return app

FlaskApp/appFlask/routes/routes.py
#from appFlask.src.database import database

from appFlask import database as db
from flask import Flask, render_template, request, redirect, url_for, Blueprint

from appFlask.data.alumnos_dao import AlumnDao
from appFlask.data.notas_dao import NotasDao  # PARA PODER ACCEDER A LOS DIRECTORIOS DE UNA MANERA FÁCIL 


app = Blueprint("routes", __name__)

@app.route('/')  # ESTO ES LA RUTA PRINCIPAL DE NUESTRA APP SE PONE CON LA BARRA
def home():
    alumnDao : AlumnDao = AlumnDao(db)
    return render_template('index.html', data=alumnDao.dameTodos())  # PARA QUE SALGA NUESTRO INDEX AL INICIO #DATA=INSERTOBJECT ES PARA QUE NOS SALGA EN NUESTRO HTML


@app.route('/user', methods=['POST'])
def addUser():
    nombre = request.form['Nombre'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL NOMBRE QUE INDIQUEMOS
    apellido = request.form['Apellido'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL password QUE INDIQUEMOS
    centroFormativo = request.form['CentroFormativo'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL NOMBRE QUE INDIQUEMOS
    alumnDao : AlumnDao = AlumnDao(db)
    alumnDao.añadirUsuario(nombre,apellido,centroFormativo)
    return redirect(url_for('routes.home')) # Y REDIRIGIMOS A HOME DE NUEVO. REDIRECT Y URL_FOR LO TENEMOS QUE IMPORTAR DE FLASK



@app.route('/edit/<string:CodigoAlumno>', methods=['POST'])
def edit (CodigoAlumno):
    Nombre = request.form['Nombre'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL NOMBRE DE USUARIO QUE INDIQUEMOs
    Apellido = request.form['Apellido'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL NOMBRE QUE INDIQUEMOS
    CentroFormativo = request.form['CentroFormativo'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL password QUE INDIQUEMOS
    alumnDao : AlumnDao = AlumnDao(db)
    alumnDao.editarUsuario(Nombre,Apellido,CentroFormativo,CodigoAlumno)
    return redirect(url_for('routes.home')) # Y REDIRIGIMOS A HOME DE NUEVO. REDIRECT Y URL_FOR LO TENEMOS QUE IMPORTAR DE FLASK
    


@app.route('/delete/<string:CodigoAlumno>')
def delete(CodigoAlumno):
    alumnDao : AlumnDao = AlumnDao(db)
    alumnDao.borrarUsuario(CodigoAlumno)
    return redirect(url_for('routes.home')) # Y REDIRIGIMOS A HOME DE NUEVO. REDIRECT Y URL_FOR LO TENEMOS QUE IMPORTAR DE FLASK


@app.route('/notas')  # ESTO ES LA RUTA PARA VER LAS NOTAS DE LOS ALUMNOS EN MI APP SE PONE CON LA BARRA
def notas():
    notasDao : NotasDao = NotasDao(db)
    return render_template('notas.html', data=notasDao.dameNotas())  # PARA QUE SALGA NUESTRO INDEX AL INICIO #DATA=INSERTOBJECT ES PARA QUE NOS SALGA EN NUESTRO HTML


@app.route('/userNotas', methods=['POST'])
def addNotas():
    CodigoAlumno = request.form['CodigoAlumno'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL CODIGO ALUMNO QUE INDIQUEMOS
    Seguridad = request.form['Seguridad'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON LA NOTA QUE INDIQUEMOS
    Implantacion = request.form['Implantacion'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON LA NOTA QUE INDIQUEMOS
    Redes = request.form['Redes']
    notasDao : NotasDao = NotasDao(db)
    notasDao.añadeNotas(CodigoAlumno,Seguridad,Implantacion,Redes)
    return redirect(url_for('routes.notas')) # Y REDIRIGIMOS A HOME DE NUEVO. REDIRECT Y URL_FOR LO TENEMOS QUE IMPORTAR DE FLASK


@app.route('/deleteNotas/<string:CodigoAlumno>')
def deleteNotas(CodigoAlumno):
    notasDao : NotasDao = NotasDao(db)
    notasDao.borrarNotas(CodigoAlumno)
    return redirect(url_for('routes.notas')) # Y REDIRIGIMOS A HOME DE NUEVO. REDIRECT Y URL_FOR LO TENEMOS QUE IMPORTAR DE FLASK


@app.route('/editNotas/<string:CodigoAlumno>', methods=['POST'])
def editNotas (CodigoAlumno):
    CodigoAlumno = request.form['CodigoAlumno'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON EL CodigoAlumno QUE INDIQUEMOS
    Seguridad = request.form['Seguridad'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON LA NOTA DE SEGURIDAD QUE INDIQUEMOS
    Implantacion = request.form['Implantacion'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON CON LA NOTA DE IMPLANTACION QUE INDIQUEMOS
    Redes = request.form['Redes'] # PARA PODER OBTENER EL CONTENIDO DEL INPUT CON LA NOTA DE REDES QUE INDIQUEMOS
    notasDao: NotasDao = NotasDao(db)
    notasDao.editNotas(Seguridad,Implantacion,Redes,CodigoAlumno)
    return redirect(url_for('routes.notas')) # Y REDIRIGIMOS A HOME DE NUEVO. REDIRECT Y URL_FOR LO TENEMOS QUE IMPORTAR DE FLASK

FlaskApp/appFlask/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>InformacionAlumno</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

FlaskApp/appFlask/templates/index.html
{% extends "base.html" %}
{% block title %}InformacionAlumno {% endblock %}


{% block content %}
<h1 class="text-center mt-5 mb-5 text-primary">ESTO ES UNA PRUEBA PARA GITHUBACTIONS</h1>
    
    <div class="container"> 
        <div class="card shadow">
            <div class="card-body">
                <form action="/user" method="POST"> <!-- PONEMOS /USER QUE ES DONDE VAN LOS DATOS QUE METAMOS-->
                    <div class="row mb-3">
                        <div class="col">
                            <label>Nombre</label>
                            <input type="text" class="form-control mb-3" name="Nombre">
                        </div>
                        <div class="col">
                            <label>Apellido</label>
                            <input type="text" class="form-control mb-3" name="Apellido">
                        </div>
                        <div class="col">
                            <label>CentroFormativo</label>
                            <input type="text" class="form-control mb-3" name="CentroFormativo">
                        </div>
                        <div class="col">
                            <button class="btn btn-primary mb-3 mt-4" type="submit">Guardar</button>
                        </div>
                    </div>

                </form>

                <!-- TABLA  -->
                
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">CodigoAlumno</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">CentroFormativo</th>
                            <th scope="col">Editar</th>
                            <th scope="col">Eliminar</th>
                        </tr>
                    </thead>
                
                <tbody>
                    {% for d in data %} <!-- ESTE BUCLE SIRVE PARA ENVIAR LOS DATOS . POR CADA UNO DE LOS ELEMENTOS DE DATA LO VAMOS A IR IMPRIMIENDO DENTRO DE DATA-->
                        <tr>
                            <td>{{d.CodigoAlumno}}</td>  <!-- LAS DOBLES LLAVES ES PARA ACCEDER A LOS DATOS. CON EL '.' ACCEDEMOS AL DATO EN CONCRETO -->
                            <td>{{d.Nombre}}</td>
                            <td>{{d.Apellido}}</td>
                            <td>{{d.CentroFormativo}}</td>
                            <td><button class="btn btn-primary btn-sm" id="btn-edit{{d.CodigoAlumno}}" data-bs-toggle="modal" data-bs-target="#modal{{d.CodigoAlumno}}">Edit</button></td>
                            <td><a href="{{url_for('routes.delete',CodigoAlumno=d.CodigoAlumno)}}" class="btn btn-danger btn-sm">Delete</a></td>
                        </tr>
                <!-- PARA CERRAR EL BUCLE -->

                        <!-- modal -->

                        <div class="modal fade" id="modal{{d.CodigoAlumno}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h1 class="modal-title fs-5" id="exampleModalLabel">{{d.Nombre}}</h1>
                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="/edit/{{d.CodigoAlumno}}" method="post">
                                        <label>Nombre</label>
                                        <input type="text" class="form-control mb-3" name="Nombre" value="{{d.Nombre}}">
                                        <label>Apellido</label>
                                        <input type="text" class="form-control mb-3" name="Apellido" value="{{d.Apellido}}">
                                        <label>CentroFormativo</label>
                                        <input type="text" class="form-control mb-3" name="CentroFormativo" value="{{d.CentroFormativo}}">
                                  
                                </div>
                                <div class="modal-footer">
                                  <button type="submit" class="btn btn-primary">Save changes</button>
                                </div>
                                </form>
                              </div>
                            </div>
                          </div>

                    {% endfor %}

                </tbody>

            </table>
            
            </div>
        </div>
    </div>

    <td><a href="{{url_for('routes.notas')}}">Notas Alumnos</a></td>
{% endblock %}

FlaskApp/appFlask/templates/notas.html
{% extends "base.html" %}
{% block title %}InformacionAlumno {% endblock %}


{% block content %}
<h1 class="text-center mt-5 mb-5 text-primary">Notas Alumnos IES Madrid ASIR</h1>

    <div class="container">
        <div class="card shadow">
            <div class="card-body">
                <form action="/userNotas" method="POST"> <!-- PONEMOS /USER QUE ES DONDE VAN LOS DATOS QUE METAMOS-->
                    <div class="row mb-3">
                        <div class="col">
                            <label>CodigoAlumno</label>
                            <input type="text" class="form-control mb-3" name="CodigoAlumno">
                        </div>
                        <div class="col">
                            <label>Seguridad</label>
                            <input type="text" class="form-control mb-3" name="Seguridad">
                        </div>
                        <div class="col">
                            <label>Implantacion</label>
                            <input type="text" class="form-control mb-3" name="Implantacion">
                        </div>
                        <div class="col">
                            <label>Redes</label>
                            <input type="text" class="form-control mb-3" name="Redes">
                        </div>
                        <div class="col">
                            <button class="btn btn-primary mb-3 mt-4" type="submit">Guardar</button>
                        </div>
                    </div>

                </form>


                <!-- TABLA  -->

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">CodigoAlumno</th>
                            <th scope="col">Seguridad</th>
                            <th scope="col">Implantacion</th>
                            <th scope="col">Redes</th>
                            <th scope="col">Editar</th>
                            <th scope="col">Eliminar</th>
                        </tr>
                    </thead>
                
                <tbody>
                    {% for d in data %} <!-- ESTE BUCLE SIRVE PARA ENVIAR LOS DATOS . POR CADA UNO DE LOS ELEMENTOS DE DATA LO VAMOS A IR IMPRIMIENDO DENTRO DE DATA-->
                        <tr>
                            <td>{{d.CodigoAlumno}}</td>  <!-- LAS DOBLES LLAVES ES PARA ACCEDER A LOS DATOS. CON EL '.' ACCEDEMOS AL DATO EN CONCRETO -->
                            <td>{{d.Seguridad}}</td>
                            <td>{{d.Implantacion}}</td>
                            <td>{{d.Redes}}</td>
                            <td><button class="btn btn-primary btn-sm" id="btn-edit{{d.CodigoAlumno}}" data-bs-toggle="modal" data-bs-target="#modal{{d.CodigoAlumno}}">Edit</button></td>
                            <td><a href="{{url_for('routes.deleteNotas',CodigoAlumno=d.CodigoAlumno)}}" class="btn btn-danger btn-sm">Delete</a></td>
                        </tr>
                <!-- PARA CERRAR EL BUCLE -->

                        <!-- modal -->

                        <div class="modal fade" id="modal{{d.CodigoAlumno}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h1 class="modal-title fs-5" id="exampleModalLabel">{{d.Seguridad}}</h1>
                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="/editNotas/{{d.CodigoAlumno}}" method="post">
                                        <label>CodigoAlumno</label>
                                        <input type="text" class="form-control mb-3" name="CodigoAlumno" value="{{d.CodigoAlumno}}">
                                        <label>Seguridad</label>
                                        <input type="text" class="form-control mb-3" name="Seguridad" value="{{d.Seguridad}}">
                                        <label>Implantacion</label>
                                        <input type="text" class="form-control mb-3" name="Implantacion" value="{{d.Implantacion}}">
                                        <label>Redes</label>
                                        <input type="text" class="form-control mb-3" name="Redes" value="{{d.Redes}}">
                                  
                                </div>
                                <div class="modal-footer">
                                  <button type="submit" class="btn btn-primary">Save changes</button>
                                </div>
                                </form>
                              </div>
                            </div>
                          </div>




                    {% endfor %}

                </tbody>

            </table>


            </div>
        </div>
    </div>
    <td><a href="{{url_for('routes.home')}}">Informacion Alumno</a></td>
{% endblock %}